//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaOlcar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingreso()
        {
            this.DetalleIngreso = new HashSet<DetalleIngreso>();
        }
    
        public int idIngreso { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int creadorPor { get; set; }
        public string tipoDocumento { get; set; }
        public string nroDocumento { get; set; }
        public System.DateTime fechaDocumento { get; set; }
        public int idOrden { get; set; }
        public int idProveedor { get; set; }
        public decimal totalNeto { get; set; }
        public decimal totalIGV { get; set; }
        public decimal costoTotal { get; set; }
        public string observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleIngreso> DetalleIngreso { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual OrdenCompra OrdenCompra { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
