//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaOlcar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenCompra()
        {
            this.DetalleOrden = new HashSet<DetalleOrden>();
            this.Ingreso = new HashSet<Ingreso>();
        }
    
        public int idOrden { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int creadoPor { get; set; }
        public int idProveedor { get; set; }
        public string situacion { get; set; }
        public decimal totalNeto { get; set; }
        public decimal totalIGV { get; set; }
        public decimal costoTotal { get; set; }
        public Nullable<System.DateTime> fechaAprobacion { get; set; }
        public Nullable<int> aprobadoPor { get; set; }
        public System.DateTime fechaCaducidad { get; set; }
        public string observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrden> DetalleOrden { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingreso> Ingreso { get; set; }
    }
}
