//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaOlcar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetalleOrden = new HashSet<DetalleOrden>();
        }
    
        public int idProducto { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public bool estado { get; set; }
        public int idMarca { get; set; }
        public string categoria { get; set; }
        public int idUbicacion { get; set; }
        public string unidadMedida { get; set; }
        public string codigoEAN { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<decimal> costoSinIGV { get; set; }
        public Nullable<decimal> precioVenta { get; set; }
        public Nullable<decimal> ganancia { get; set; }
        public int stockMinimo { get; set; }
        public int stockMaximo { get; set; }
        public long stock { get; set; }
        public byte[] imagen { get; set; }
    
        public virtual MarcaProducto MarcaProducto { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrden> DetalleOrden { get; set; }
    }
}
